// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tqjvynnnxporpqetdtln.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRxanZ5bm5ueHBvcnBxZXRkdGxuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1NTUxMzMsImV4cCI6MjA1ODEzMTEzM30.XUnuZZLV4Lm1qtt8S_z_LbDh-9yXTyvT3E8KKeJZP4c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);